import React, { useState } from 'react';
import './App.css';

import TopBar from './components/layout/TopBar';
import LeftNavPanel from './components/layout/LeftNavPanel';
import CentralFormContainer from './components/layout/CentralFormContainer';
import RightPreviewPanel from './components/layout/RightPreviewPanel';

// Import export libraries at runtime. (See further below in code)

/**
 * ResumeGenie Main Container App
 * Lays out the app with TopBar, LeftNavPanel, CentralFormContainer, and RightPreviewPanel.
 *
 * Manages main app navigation section state and passes handlers to nav and form containers.
 * Adds preview mode toggle (Resume vs Cover Letter), disabled stubs for AI/export.
 * 
 * PUBLIC_INTERFACE
 */
function App() {
  // Canonical section IDs for navigation/app steps
  const sections = [
    { id: 'personal', label: 'Personal Info' },
    { id: 'education', label: 'Education' },
    { id: 'experience', label: 'Experience' },
    // Add further sections as needed, e.g. skills, projects etc
    { id: 'projects', label: 'Projects (optional)', optional: true },
    { id: 'skills', label: 'Skills' },
    { id: 'certifications', label: 'Certifications (optional)', optional: true },
    { id: 'achievements', label: 'Achievements (optional)', optional: true }
  ];

  // Maintain active section as state
  const [activeSection, setActiveSection] = useState(sections[0].id);

  // Selected template for preview/export
  const [selectedTemplate, setSelectedTemplate] = useState('Modern');

  // Preview mode: 'resume' or 'cover'
  const [previewMode, setPreviewMode] = useState('resume');

  // LIFTED form data/state for real-time preview (formerly in CentralFormContainer)
  const [formData, setFormData] = useState({
    personal: {
      fullName: '', email: '', phone: '', address: ''
    },
    education: [{
      school: '', degree: '', startDate: '', endDate: '', description: ''
    }],
    experience: [{
      jobTitle: '', employer: '', startDate: '', endDate: '', description: ''
    }],
    projects: [],
    skills: [],
    certifications: [],
    achievements: [],
  });

  // Panel preview visibility state
  const [previewOpen, setPreviewOpen] = useState(true);

  // Utility to format data into "resume" text blocks (for PDF/Word export)
  function formatResumeData({ formData, selectedTemplate, previewMode }) {
    // This is a minimal/basic formatter. This can be replaced later by a template engine.
    const { personal, education, experience, projects, skills, certifications, achievements } = formData;
    let content = '';
    content += `${personal.fullName || ''}\n${personal.email || ''} | ${personal.phone || ''} | ${personal.address || ''}\n\n`;

    if (previewMode === 'cover') {
      content += `Cover Letter\n\n[Replace this with custom letter content...]\n\n`;
      // Optionally map more sections.
      return content;
    }

    content += `Education:\n`;
    (education || []).forEach(ed =>
      content += `- ${ed.degree || ''} at ${ed.school || ''} (${ed.startDate || ''} - ${ed.endDate || ''})\n  ${ed.description || ''}\n`
    );

    content += `\nExperience:\n`;
    (experience || []).forEach(ex =>
      content += `- ${ex.jobTitle || ''} at ${ex.employer || ''} (${ex.startDate || ''} - ${ex.endDate || ''})\n  ${ex.description || ''}\n`
    );

    if ((projects && projects.length)) {
      content += `\nProjects:\n`;
      projects.forEach(pr =>
        content += `- ${pr.title || ''} (${pr.link || ''})\n  ${pr.details || ''}\n`
      );
    }

    if ((skills && skills.length)) {
      content += `\nSkills:\n${skills.join(', ')}\n`;
    }
    if ((certifications && certifications.length)) {
      content += `\nCertifications:\n`;
      certifications.forEach(cert =>
        content += `- ${cert.name || ''}, issued by ${cert.issuer || ''}, ${cert.date || ''}\n`
      );
    }
    if ((achievements && achievements.length)) {
      content += `\nAchievements:\n`;
      achievements.forEach(ach =>
        content += `- ${ach.title || ''}: ${ach.description || ''}\n`
      );
    }
    content += `\n\nGenerated by ResumeGenie with template: ${selectedTemplate}\n`;
    return content;
  }

  /**
   * PUBLIC_INTERFACE - Exports the resume or cover letter as PDF or DOCX based on user action.
   * @param {'pdf'|'docx'} exportType - The format to export (PDF/DOCX)
   */
  const handleExport = async exportType => {
    // Generate content from form data and template
    const docTitle = previewMode === 'cover' ? 'CoverLetter' : 'Resume';
    const fileName = `${docTitle}_${formData.personal.fullName || 'Document'}`;
    const text = formatResumeData({ formData, selectedTemplate, previewMode });

    if (exportType === 'pdf') {
      // Dynamically import jsPDF for size optimization
      try {
        const { jsPDF } = await import('jspdf');
        const doc = new jsPDF({
          orientation: 'portrait',
          unit: 'pt',
          format: 'a4',
        });
        // Set font and add content
        doc.setFont('helvetica', 'normal');
        // We define a simple margin and max width for readability
        const margin = 44, maxWidth = 525;
        doc.setFontSize(13);
        doc.text(text, margin, 60, { maxWidth });
        doc.save(`${fileName}.pdf`);
      } catch (err) {
        alert('PDF export unavailable. Please ensure jsPDF is installed!');
      }
    } else if (exportType === 'docx') {
      // Lazy-load docx library for size optimization
      try {
        const docx = await import('docx');
        const { Document, Packer, Paragraph, TextRun } = docx;
        // Split into lines for simple formatting
        const lines = text.split('\n');
        const doc = new Document({
          sections: [{
            children: lines.map(l =>
              new Paragraph({ children: [new TextRun({ text: l || ' ', font: "Arial", size: 24 })] })
            ),
          }]
        });
        const blob = await Packer.toBlob(doc);
        // Download utility
        const a = document.createElement('a');
        a.href = URL.createObjectURL(blob);
        a.download = `${fileName}.docx`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
      } catch (err) {
        alert('Word (DOCX) export unavailable. Please ensure docx is installed!');
      }
    }
  };

  // Placeholder: AI content enhancement (future)
  const handleAISuggest = () => {
    alert('AI-powered suggestions will be available soon.');
  };

  // Optionally pass more feature flags for future toggling
  return (
    <div className="app" tabIndex={-1}>
      <TopBar
        selectedTemplate={selectedTemplate}
        onTemplateChange={setSelectedTemplate}
        // PUBLIC_INTERFACE: onExport handler accepts exportType: 'pdf' | 'docx'
        onExport={handleExport}
        previewMode={previewMode}
        onTogglePreviewMode={() => setPreviewMode(m => (m === 'resume' ? 'cover' : 'resume'))}
        previewOpen={previewOpen}
        onTogglePreviewPanel={() => setPreviewOpen(val => !val)}
        // Future props for AI/export/menu controls
      />
      <main
        className="main-container"
        style={{
          display: 'flex',
          flex: 1,
          minHeight: '100vh',
          marginTop: 64 // height of TopBar (fixed)
        }}
        aria-label="Main content area"
      >
        <LeftNavPanel
          sections={sections}
          activeSection={activeSection}
          onSectionChange={setActiveSection}
          // Future: Props for analytics, section-completion etc
        />
        <CentralFormContainer
          sectionId={activeSection}
          sectionLabel={sections.find(s => s.id === activeSection)?.label || ''}
          previewMode={previewMode}
          onAISuggest={handleAISuggest}
          // Pass formData and updater as CONTROLLED PROPS
          formData={formData}
          setFormData={setFormData}
          previewOpen={previewOpen}
          onTogglePreviewPanel={() => setPreviewOpen(val => !val)}
        />
        <RightPreviewPanel
          activeSection={activeSection}
          selectedTemplate={selectedTemplate}
          previewMode={previewMode}
          formData={formData}
          previewOpen={previewOpen}
          onTogglePreviewPanel={() => setPreviewOpen(val => !val)}
        />
      </main>
    </div>
  );
}

export default App;